### ISSUE TITLE
Category and Sponsor fields in posts - display issue

### ISSUE THREAD

**Issue by nilovna** [mtlpy/mtlpyweb#117]
When creating a new post in Django admin - You can't see which are the category names, as their display name is `Category Object`

--- Category field
![screen shot 2018-01-17 at 13 31 27](https://user-images.githubusercontent.com/906237/35059998-00db4a32-fb8b-11e7-8570-3ca53262af57.png)

--- Sponsor field
![screen shot 2018-01-17 at 13 33 42](https://user-images.githubusercontent.com/906237/35060027-1aedf3c0-fb8b-11e7-996b-7a6c3d80118a.png)

--- On website
![screen shot 2018-01-17 at 13 40 20](https://user-images.githubusercontent.com/906237/35060286-fecaca3c-fb8b-11e7-8aa3-bb5e8f59858d.png)

**Comment by merwok** [comment]
IMO there should be two fixes: add `__str__` to models for the admin; change the template to be explicit e.g. `{{ post.category.name }}` and not rely on `__str__`.

Je peux faire une PR mais pas tester localement.

**Comment by mlhamel** [comment]
Je pourrai tester !

**Comment by merwok** [comment]
Le CI pète et le test runner ne donne aucune information utile ¯\_(ツ)_/¯
