### ISSUE TITLE
wiki.montrealpython.org leads to the django site

### ISSUE THREAD

**Issue by rgeoghegan** [mtlpy/mtlpyweb#17]
The nginx config (at conf/website-prod.nginx) accepts connections to wiki.montrealpython.org, and passes them to django. I added wiki.montrealpython.org to the allowed hosts environmental variable, so django will take it, but it really shouldn't.

**Comment by peristeri** [comment]
I don't think the wiki is maintained. It should be removed from the nginx config

**Comment by pior** [comment]
wiki.montrealpython.org is not used anymore. 
DNS record was removed during Heroku migration

**Comment by merwok** [comment]
Par hasard, on a un dump des données quelque part? Il y avait du contenu d’atelier par exemple.

**Comment by pior** [comment]
@merwok -> #58
