### ISSUE TITLE
Two problems in the sidebar in blogpost

### ISSUE THREAD

**Issue by andrefarzat** [mtlpy/mtlpyweb#21]
Hey, guys. I made a screenshot to make it easier to explain: 
![screen shot 2014-11-11 at 11 37 36 pm](https://cloud.githubusercontent.com/assets/649219/5005424/162880d6-69fc-11e4-905c-ee4220de6dc6.png)

**Comment by peristeri** [comment]
I can no longer reproduce this exact problem. Closing
