### ISSUE TITLE
Fix exception when blog post doesn't have any publish date

### ISSUE THREAD

**Issue by mlhamel** [mtlpy/mtlpyweb#25]
strange but it happen...

**Comment by merwok** [comment]
C’est peut-être lié à une erreur dans l’import initial, ou à des données manquantes. Est-ce que ce changement ne va pas cacher des posts? L’alternative serait d’ajouter des if dans les templates, ou une property sur le modèle qui masque la donnée manquante.

Merci pour le fix en tout cas.
