### ISSUE TITLE
Fix the video section

### ISSUE THREAD

**Issue by agrant3d** [mtlpy/mtlpyweb#4]
Original issue: https://github.com/mtlpy/mtlpy-django-abandoned/issues/25
Right now we are parsing at each reload the feed from youtube but it only give us the most popular videos.

We should find a way to get all the videos or to create a model which will allow us to save videos links in the db and associated them with the following fields:

- Title
- Description
- Event (MP40, 41, 42, 43, 44, ...)
- Speaker(s)

We should group those videos by event in the model and maybe associated them with the blog post.

**Comment by peristeri** [comment]
I think the video page is good enough
