### ISSUE TITLE
Use cookie for sessions

### ISSUE THREAD

**Issue by pior** [mtlpy/mtlpyweb#43]

**Comment by merwok** [comment]
:cookie: :cookie:

**Comment by pior** [comment]
Given the huge drawback of the django cookiestore, we should probably avoid using it.

https://docs.djangoproject.com/en/1.11/topics/http/sessions/#using-cookie-based-sessions

**Comment by merwok** [comment]
I see in the settings that we don’t configure a specific session backend; is the default for this django version database with session ID in signed cookie?

**Comment by pior** [comment]
Yes, random id in cookie + entry in DB.
Here, the initial intention was to avoid clogging the DB with a growing table. 
Maybe we can just clean the table somehow.

**Comment by merwok** [comment]
Run a command to clear sessions during the release phase? (erk)

**Comment by merwok** [comment]
If there is a free redis add-on for heroku, django-redis-sessions could be a good option.
