### ISSUE TITLE
Keep Discus or Remove it?

### ISSUE THREAD

**Issue by pior** [mtlpy/mtlpyweb#82]
Do we really need comments on the website, when we have so many communication channels?

Slack, Meetup, Facebook, Linkedin, Tweeter ...

@mtlpy/mtlpyweb

**Comment by merwok** [comment]
Is there significant discussion on articles?  Maybe the contact form is enough for people asking about events, and the mailing list good for discussions.

**Comment by mlhamel** [comment]
I dunno, historically there's not that many comments. At the same time the overhead doesn't seems such a big deal. I'm really a big fan of having a lot of communication channels.

**Comment by merwok** [comment]
Who’s looking at comments and moderating when needed?

**Comment by pior** [comment]
Yeah, this seems like a forgotten land.

I'm quite happy with many communication channels as well. 

This one seems almost not used, and when it is, I think it's usually a question that's left unanswered.
