### ISSUE TITLE
CI broken after switch to Pipfile

### ISSUE THREAD

**Issue by merwok** [mtlpy/mtlpyweb#94]

**Comment by pior** [comment]
Ah on a vraiment un CI? :trollface:

**Comment by merwok** [comment]
Hum CircleCI s’est mis à me montrer des builds rouge pour master, j’ai cru que ça voulait dire qu’on avait un setup. Ça doit être un glitch, j’ai unfollowé le projet.

**Comment by pior** [comment]
Tu avais tout à fait raison : j'avais simplement oublié qu'on avait réellement un CI qui tournait.
En fait il fait pas grand chose, mais bon je l'ai bel et bien brisé.

**Comment by merwok** [comment]
Au moins ça ne bloque pas les PR!
